In [33]:
import torch
import numpy as np

In [34]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [35]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [36]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.3215, 0.7532],
        [0.0987, 0.1442]]) 



In [37]:
bool_tensor = torch.tensor([[True, False], [False, True]], dtype=torch.bool)
print(bool_tensor.shape)
print(bool_tensor)

int16_tensor = torch.tensor([[1, 2], [3, 4]], dtype=torch.int16)
print(int16_tensor)

floats_tensor = torch.tensor([[1.0, 2.0], [3.0, 4.0]], dtype=torch.float32)
print(floats_tensor)


torch.Size([2, 2])
tensor([[ True, False],
        [False,  True]])
tensor([[1, 2],
        [3, 4]], dtype=torch.int16)
tensor([[1., 2.],
        [3., 4.]])


In [38]:
x = torch.rand(3, 4)
if torch.cuda.is_available():
    x = x.to('cuda')
    print(x)
    print(x.device)
    print(x.shape)
print(x)
print(x.device)
print(x.shape)

tensor([[0.9573, 0.6429, 0.2772, 0.5094],
        [0.8376, 0.8523, 0.4929, 0.9120],
        [0.6421, 0.5715, 0.7294, 0.2735]])
cpu
torch.Size([3, 4])


In [39]:
#slicing demo
x = torch.rand(5, 5)
print(x)
print(x[0]) # first row
print(x[:, 0]) # first column
print(x[0, :]) # first row
print(x[1:3, 1:3]) # middle 2x2


tensor([[0.7669, 0.7333, 0.7084, 0.1232, 0.9773],
        [0.6947, 0.1925, 0.0604, 0.9659, 0.3862],
        [0.3787, 0.2498, 0.3037, 0.8753, 0.4996],
        [0.7794, 0.5612, 0.1209, 0.4384, 0.0614],
        [0.5567, 0.1226, 0.4806, 0.3429, 0.4801]])
tensor([0.7669, 0.7333, 0.7084, 0.1232, 0.9773])
tensor([0.7669, 0.6947, 0.3787, 0.7794, 0.5567])
tensor([0.7669, 0.7333, 0.7084, 0.1232, 0.9773])
tensor([[0.1925, 0.0604],
        [0.2498, 0.3037]])


In [40]:
x = torch.rand(2,2)
print(x)
print()
x_cat_0 = torch.cat([x, x], dim=0) # concatenate along rows
print(x_cat_0)
print()
x_cat_1 = torch.cat([x, x], dim=1) # concatenate along columns
print(x_cat_1)
print()

tensor([[0.4201, 0.5009],
        [0.9856, 0.3168]])

tensor([[0.4201, 0.5009],
        [0.9856, 0.3168],
        [0.4201, 0.5009],
        [0.9856, 0.3168]])

tensor([[0.4201, 0.5009, 0.4201, 0.5009],
        [0.9856, 0.3168, 0.9856, 0.3168]])



In [41]:
#mulitplication

x2 = torch.tensor([[1, 2], [3, 4]])
print(x1)
print()
print(x2)
print()
print(x1 * x2) # element-wise multiplication
print()
print(torch.matmul(x1, x2)) # matrix multiplication
print()
print(torch.multiply(x1, x2)) # element-wise multiplication

tensor([[1, 2],
        [3, 4]])

tensor([[1, 2],
        [3, 4]])

tensor([[ 1,  4],
        [ 9, 16]])

tensor([[ 7, 10],
        [15, 22]])

tensor([[ 1,  4],
        [ 9, 16]])


In [49]:
x1 = torch.tensor([[1, 2], [3, 4]])
print(x1)
print()
x1.add_(x1) # in-place addition
print(x1)
print()
x1 = torch.tensor([[1, 2], [3, 4]])
x1.add(x1) # out-of-place addition
print(x1)


tensor([[1, 2],
        [3, 4]])

tensor([[2, 4],
        [6, 8]])

tensor([[1, 2],
        [3, 4]])
