In [17]:
import torch
x = torch.randn(3,requires_grad=True)
print(x)
y = x +2
print(y)

z = y * y * 2
z = z.mean()
print(z)
z = z.backward()
print(x.grad)

tensor([ 1.5503, -0.1534, -0.7811], requires_grad=True)
tensor([3.5503, 1.8466, 1.2189], grad_fn=<AddBackward0>)
tensor(11.6670, grad_fn=<MeanBackward0>)
tensor([4.7337, 2.4622, 1.6253])
