In [13]:
import torch

class TinyModel(torch.nn.Module):
    def __init__(self):
        super(TinyModel, self).__init__()
        self.layer1 = torch.nn.Linear(100,200)
        self.activation = torch.nn.ReLU()
        self.layer2 = torch.nn.Linear(200,10)
        self.softmax = torch.nn.Softmax()

    def forward(self, x):
        x = self.layer1(x)
        x = self.activation(x)
        x = self.layer2(x)
        x = self.softmax(x)
        return x
    
tinymoddel = TinyModel()
print("The model")
print(tinymoddel)

print("The model parameters")
for prams in tinymoddel.parameters():
    print(prams)

The model
TinyModel(
  (layer1): Linear(in_features=100, out_features=200, bias=True)
  (activation): ReLU()
  (layer2): Linear(in_features=200, out_features=10, bias=True)
  (softmax): Softmax(dim=None)
)
The model parameters
Parameter containing:
tensor([[-0.0571, -0.0396,  0.0874,  ..., -0.0340,  0.0377, -0.0482],
        [ 0.0769, -0.0984,  0.0151,  ..., -0.0867,  0.0336, -0.0227],
        [ 0.0857, -0.0504,  0.0403,  ...,  0.0221, -0.0743,  0.0648],
        ...,
        [ 0.0801,  0.0466,  0.0163,  ...,  0.0873, -0.0900, -0.0476],
        [-0.0355, -0.0937, -0.0013,  ..., -0.0756, -0.0593,  0.0434],
        [ 0.0527, -0.0674,  0.0062,  ..., -0.0961, -0.0094, -0.0336]],
       requires_grad=True)
Parameter containing:
tensor([-0.0343, -0.0787, -0.0575,  0.0206, -0.0377, -0.0996,  0.0842, -0.0407,
        -0.0227,  0.0698,  0.0618,  0.0309,  0.0938,  0.0228, -0.0790,  0.0893,
        -0.0928,  0.0113,  0.0361,  0.0618,  0.0765, -0.0469,  0.0861,  0.0375,
        -0.0289, -0.0252, -0

In [14]:
lin = torch.nn.Linear(3,2)
x = torch.rand(1,3)
print(x)

print("The weights and bias of the linear layer")
for prams in lin.parameters():
    print(prams)

y = lin(x)
print(y)

tensor([[0.6486, 0.6306, 0.2338]])
The weights and bias of the linear layer
Parameter containing:
tensor([[ 0.2808, -0.2008, -0.1878],
        [ 0.4401, -0.2518, -0.3793]], requires_grad=True)
Parameter containing:
tensor([-0.4989, -0.5126], requires_grad=True)
tensor([[-0.4873, -0.4746]], grad_fn=<AddmmBackward0>)


In [ ]:
import torch.functional as F

class LeNet(torch.nn.Module):
    def __init__(self):
        super(LeNet, self).__init__()
        self.conv1 = torch.nn.Conv2d(1, 6, 5)
        self.pool = torch.nn.MaxPool2d(6,16,3)
        self.fc1 = torch.nn.Linear(6*6*6, 120)
        self.fc2 = torch.nn.Linear(120, 84)
        self.fc3 = torch.nn.Linear(84, 10)

    def forward(self, x):
        x = F.max_pool2d(F.relu(self.conv1(x)), (2,2))
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x
    
    def num_flat_features(self, x):
        size = x.size()[1:]
        num_features = 1
        for s in size:
            num_features *= s
        return num_features
    

lenet = LeNet()
print("The model")
print(lenet)

print("The model parameters")
for prams in lenet.parameters():
    print(prams)

x = torch.rand(1,1,32,32)
print(x)


    

The model
LeNet(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (pool): MaxPool2d(kernel_size=6, stride=16, padding=3, dilation=1, ceil_mode=False)
  (fc1): Linear(in_features=216, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)
The model parameters
Parameter containing:
tensor([[[[ 0.1869,  0.0331,  0.0754, -0.0900, -0.0068],
          [ 0.0689, -0.0230,  0.0768, -0.1529, -0.0131],
          [-0.1561, -0.0016, -0.1677,  0.0343,  0.1006],
          [-0.1705,  0.0982, -0.1874, -0.0258,  0.0345],
          [-0.0690, -0.0814,  0.0844, -0.1332, -0.0800]]],


        [[[-0.0706,  0.0636,  0.0598, -0.0802,  0.0620],
          [ 0.1879, -0.1364,  0.0710,  0.0657, -0.1742],
          [-0.0615,  0.0577,  0.1757,  0.1415,  0.1819],
          [-0.1617,  0.0558,  0.0813,  0.0996,  0.0638],
          [ 0.0569,  0.0217,  0.1182, -0.0103, -0.0704]]],


        [[[ 0.1088,  0.0148,  0.

AttributeError: module 'torch.functional' has no attribute 'max_pool2d'

In [ ]:
class LSTMTagger(torch.nn.Module):
    def __init__(self, embedding_dim, hidden_dim, vocab_size, tagset_size):
        super(LSTMTagger, self).__init
        self.hidden_dim = hidden_dim
        self.word_embeddings = torch.nn.Embedding(vocab_size, embedding_dim)
        self.lstm = torch.nn.LSTM(embedding_dim, hidden_dim)
        self.hidden2tag = torch.nn.Linear(hidden_dim, tagset_size)
        self.hidden = self.init_hidden()

    def forward(self, sentence):
        embeds = self.word_embeddings(sentence)
        lstm_out, self.hidden = self.lstm(embeds.view(len(sentence), 1, -1), self.hidden)
        tag_space = self.hidden2tag(lstm_out.view(len(sentence), -1))
        tag_scores = F.log_softmax(tag_space, dim=1)
        return tag_scores