In [37]:
import torch
import math

In [38]:
x = torch.empty(3, 4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[0.3126, 0.3791, 0.3087, 0.0736],
        [0.4216, 0.0691, 0.2332, 0.4047],
        [0.2162, 0.9927, 0.4128, 0.5938]])


In [39]:
zeros = torch.zeros(3, 4)
print(zeros)

ones = torch.ones(3, 4)
print(ones)


torch.manual_seed(1729)
randoms = torch.rand(3, 4)
print(randoms)


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0.3126, 0.3791, 0.3087, 0.0736],
        [0.4216, 0.0691, 0.2332, 0.4047],
        [0.2162, 0.9927, 0.4128, 0.5938]])


In [40]:
x = torch.empty(2,2,3)
print(x.shape)
print(x)

torch.Size([2, 2, 3])
tensor([[[-1.9737e-31,  8.3237e-43,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]])


In [41]:
empty_like = torch.empty_like(x)
print(empty_like.shape)
print(empty_like)

torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [42]:
zeros_like = torch.zeros_like(x)
print(zeros_like.shape)
print(zeros_like)


torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [43]:
some_constants = torch.tensor([[math.pi, math.e], [math.sqrt(2), math.sqrt(3)]])
print(some_constants.shape)
print(some_constants)

torch.Size([2, 2])
tensor([[3.1416, 2.7183],
        [1.4142, 1.7321]])


In [44]:
some_ints = torch.tensor((1, 2, 3, 4))
print(some_ints.shape)
print(some_ints)

torch.Size([4])
tensor([1, 2, 3, 4])


In [45]:
some_ints2 = torch.tensor([[1, 2], (3, 4)])
print(some_ints2.shape)
print(some_ints2)

torch.Size([2, 2])
tensor([[1, 2],
        [3, 4]])
